title: CID
description: Chemical Infrastructure Development | Innovative Chemistry for a Sustainable Future. Συμβάλλουμε στην βελτιστοποίηση των διαδικασιών επεξεργασίας λυμάτων και στην διαχείρηση της μονάδας σας με τον πλέον αποτελεσματικό και βιώσιμο τρόπο.
# timezone: UTC
collections:
  services:
    title: Services
    output: true
    permalink: /services/:path/
baseurl: ''
url: https://cid-studies.com
permalink: pretty
highlighter: rouge
sass:
    style: compressed
    sourcemap: always
plugins:
- jekyll-feed
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/