title: CID
description: Meta description
# timezone: UTC
collections:
  services:
    title: Services
    output: true
    permalink: /services/:title
baseurl: ''
url: https://cid-studies.com
permalink: pretty
highlighter: rouge
sass:
    style: compressed
    sourcemap: always
plugins:
- jekyll-feed
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/