back:
  title:
    en: Services
    el: Υπηρεσιες
  url: /services

page:
  title: 
    en: Services
    el: Υπηρεσίες
  cta:
    title: 
      en: See details
      el: Δείτε αναλυτικά

include: 
  title: 
    en: Services
    el: Εύρος υπηρεσιών
  cta:
    title: 
      en: See details
      el: Δείτε αναλυτικά
    url: /services