title: "Εύρος υπηρεσιών"
cta_text: "Δείτε αναλυτικά"
cta_link: "/services"

items:
  - title: "Ίδρυση & Αδειοδότηση"
    link: "/services/permits"
    color_class: "bg-orange"
    details:
      - "Έγκριση-Γνωστοποίηση Εγκατάστασης / Μελέτη"
      - "Εκτίμησης Περιβαλλοντικών Επιπτώσεων (ΜΠΕ)"
      - "Μελέτη και Αδειοδότηση Συστημάτων Επεξεργασίας & Διάθεσης Αποβλήτων"
      - "Άδεια Δυνατότητας Παραγωγής"
      - "Ειδική Άδεια Παραγωγής"

  - title: "Μελέτες και υλοποίηση λύσεων"
    link: "/services/studies"
    color_class: "bg-brand"
    details:
      - "Ανάκτηση και επαναχρησιμοποίηση νερού"
      - "Απολύμανση - Απόσμηση"
      - "Μελέτη και εφαρμογή ενζυμικών προϊόντων"
      - "Μελέτες (Οικονομικές, Μηχανολογικές, Ηλεκτρολογικές, Ηλεκτρονικές, Βιομηχανικές, Χημικές κ.α.)"

  - title: "Βιώσιμη Ανάπτυξη / Περιβαλλοντικές Υπηρεσίες"
    link: "/services/sustainability"
    color_class: "bg-green"
    details:
      - "Μελέτες (εγκαταστάσεων αντιρρυπαντικής τεχνολογίας, επεξεργασίας και παροχής νερού, διαχείρισης αποβλήτων, κ.α.)"
      - "Ανάπτυξη και σχεδιασμός συστημάτων περιβαλλοντικής διαχείρισης και ποιότητας"
      - "Περιβαλλοντικός έλεγχος (Eco Audit)"
